import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { Terminal, AlertCircle, Check } from 'lucide-react';
import { exerciseRepo } from '../../db/db';
import { PageHeader } from '../../components/PageHeader/PageHeader';
import type { MuscleId, EquipmentId } from '../../types/domain';
import s from './AIImport.module.css';

const ExerciseSchema = z.object({
    name: z.string(),
    mode: z.enum(['strength_reps', 'bodyweight_reps', 'timed_hold', 'cardio_duration', 'cardio_distance']),
    musclesPrimary: z.array(z.string()).optional(),
    musclesSecondary: z.array(z.string()).optional(),
    equipment: z.array(z.string()).optional(),
});

export function AIImport() {
    const navigate = useNavigate();
    const [json, setJson] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState(false);

    const handleImport = async () => {
        try {
            setError(null);
            const parsed = JSON.parse(json);
            const arr = Array.isArray(parsed) ? parsed : [parsed];
            const result = z.array(ExerciseSchema).safeParse(arr);

            if (!result.success) {
                setError('Invalid schema. Check JSON format and required fields.');
                return;
            }

            const toAdd = result.data.map(ex => ({
                id: crypto.randomUUID(),
                name: ex.name,
                mode: ex.mode,
                musclesPrimary: (ex.musclesPrimary ?? []) as MuscleId[],
                musclesSecondary: (ex.musclesSecondary ?? []) as MuscleId[],
                equipment: (ex.equipment ?? []) as EquipmentId[],
                isCustom: true,
            }));

            await exerciseRepo.bulkAdd(toAdd);
            setSuccess(true);
            setTimeout(() => navigate('/exercises'), 1200);
        } catch {
            setError('Failed to parse JSON.');
        }
    };

    return (
        <div className={s.page}>
            <PageHeader title="AI Import" />

            <div className={s.info}>
                <div className={s.infoHeader}>
                    <Terminal size={16} /> Paste JSON
                </div>
                <p className={s.helper}>Import custom exercises generated by AI tools in one step.</p>
                <textarea
                    className={s.textarea}
                    value={json}
                    onChange={e => setJson(e.target.value)}
                    placeholder={`[\n  {\n    "name": "Barbell Row",\n    "mode": "strength_reps",\n    "musclesPrimary": ["UpperBack","Biceps"]\n  }\n]`}
                />
            </div>

            {error && (
                <div className={s.error}>
                    <AlertCircle size={16} /> {error}
                </div>
            )}
            {success && (
                <div className={s.success}>
                    <Check size={16} /> Imported successfully! Redirecting…
                </div>
            )}

            <button className={s.importBtn} onClick={handleImport} disabled={!json || success}>
                Import Exercises
            </button>

            <p className={s.tip}>
                Tip: Ask ChatGPT to "generate a JSON array of exercises with name, mode, and musclesPrimary".
            </p>
        </div>
    );
}
